spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    clean-on-validation-error: false
  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      base-path: "/application-check"
      exposure:
        include: "flyway, health,metrics"
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
    shutdown:
      enabled: true
  health:
    defaults:
      enabled: true